// Render and write the generated composition flake that folds every plugin's
// cogboxPlugins.<attr>.module (plus the per-instance user flake) into one module.
//
// The file is a pure function of config.json's .plugins array plus the
// on-disk plugin sources, and is regenerated on every plugin mutation;
// cogbox-launch.sh points --override-input userExtensions at its directory
// when plugins exist.
//
// Each plugin input resolves OFFLINE at launch: when the plugin's source has
// been materialized on the persistent PVC (has_source), the input is a `path:`
// ref read straight from disk (no fetcher, so no network and no credential
// needed at launch -- which is the whole point: launch has no token). A
// `git+http(s)` input pinned by ?ref=&rev= cannot be made offline (nix's git
// fetcher re-contacts the remote to verify the rev on a fresh store), so the
// locked git URL is only a migration fallback for a plugin added before the
// source was materialized.

const std = @import("std");

pub const PluginRef = struct {
	name: []const u8,
	locked_url: []const u8,
	attr: []const u8 = "default", // nixosModules attr to import
	// Whether this plugin's source has been materialized under
	// <sources_dir>/<name>; when true, render emits a `path:` input (offline)
	// instead of the locked git/tarball URL. Set by the caller from a
	// filesystem check, so render stays a pure function of config + disk.
	has_source: bool = false,
	// The flake's subdir (`?dir=` query param) when the plugin lives in a
	// subdir of its repo. The materialized source is the repo ROOT, so the
	// path: input must carry `?dir=<dir>` to locate the flake. null = repo root.
	dir: ?[]const u8 = null,
};

pub const RenderError = error{
	NoPlugins,
	OutOfMemory,
};

/// Render the composition flake. Plugin inputs are named "p-<name>" (quoted
/// attrs) so they can never collide with `user`/`self`; the user flake is
/// always imported, last. `sources_dir` is the absolute base dir under which
/// each materialized plugin source lives (<sources_dir>/<name>); a plugin with
/// has_source=true points its input there as `path:` (offline at launch),
/// otherwise it falls back to the locked git/tarball URL (migration path).
pub fn render(
	allocator: std.mem.Allocator,
	instance: []const u8,
	user_flake_dir: []const u8,
	sources_dir: []const u8,
	plugins: []const PluginRef,
) RenderError![]u8 {
	if (plugins.len == 0) return error.NoPlugins;

	var out: std.ArrayList(u8) = .empty;
	defer out.deinit(allocator);

	try out.appendSlice(allocator, "# GENERATED by 'cogbox plugin' -- DO NOT EDIT.\n" ++
		"# Regenerated from config.json (.plugins) on every plugin add/del/update.\n" ++
		"{\n" ++
		"\tdescription = \"cogbox plugin composition for instance '");
	try out.appendSlice(allocator, instance);
	try out.appendSlice(allocator, "'\";\n\n\tinputs = {\n\t\tuser.url = \"path:");
	try appendNixString(allocator, &out, user_flake_dir);
	try out.appendSlice(allocator, "\";\n");
	for (plugins) |p| {
		try out.appendSlice(allocator, "\t\t\"p-");
		try out.appendSlice(allocator, p.name);
		try out.appendSlice(allocator, "\".url = \"");
		if (p.has_source) {
			// Offline at launch: read the materialized source from disk. For a
			// subdir flake (`?dir=`) the materialized tree is the repo root, so
			// carry the same dir param to locate the flake within it.
			try out.appendSlice(allocator, "path:");
			try appendNixString(allocator, &out, sources_dir);
			try out.append(allocator, '/');
			try appendNixString(allocator, &out, p.name);
			if (p.dir) |d| {
				try out.appendSlice(allocator, "?dir=");
				try appendNixString(allocator, &out, d);
			}
		} else {
			// Not yet hydrated (added before source materialization): fall
			// back to the locked URL. A git+ URL still needs the network at
			// launch -- the path: rewrite above is the actual offline fix.
			try appendNixString(allocator, &out, p.locked_url);
		}
		try out.appendSlice(allocator, "\";\n");
	}
	try out.appendSlice(allocator, "\t};\n\n" ++
		"\toutputs = { self, user, ... }@inputs: {\n" ++
		"\t\tnixosModules.default = {\n" ++
		"\t\t\timports = [\n");
	for (plugins) |p| {
		// Import the plugin's module via its cogboxPlugins.<attr>.module
		// reference; `or {}` makes the module optional (a pure-policy plugin
		// that only contributes networkRules/l7Rules/inject omits it).
		//
		// The `_file` wrapper carries PROVENANCE into the module system. The
		// merged config.cogbox the guest brain reads is anonymous -- every
		// contents root is just some /nix/store/...-source path, which is why
		// a cross-plugin skill-name collision used to fail the build naming no
		// plugin. nixpkgs passes a module's `_file` down as the fallback file
		// for each inline module it imports (lib/modules.nix: loadModule hands
		// the parent's _file to unifyModuleSyntax, which takes
		// `_file = toString m._file or file`), and a plugin's module is a bare
		// FUNCTION out of a flake output carrying no _file of its own -- so it
		// inherits "p-<name>" from this wrapper, all the way down to the
		// option definition. flake.nix then reads
		// options.cogbox.contents.definitionsWithLocations to learn which
		// plugin contributed which root, and qualifies colliding unit names as
		// "<plugin>-<unit>" instead of refusing to build. The user flake gets
		// the "cogbox-user" marker so the brain can leave the instance's OWN
		// content unqualified.
		try out.appendSlice(allocator, "\t\t\t\t{ _file = \"p-");
		try appendNixString(allocator, &out, p.name);
		try out.appendSlice(allocator, "\"; imports = [ (inputs.\"p-");
		try out.appendSlice(allocator, p.name);
		try out.appendSlice(allocator, "\".cogboxPlugins.\"");
		try out.appendSlice(allocator, p.attr);
		try out.appendSlice(allocator, "\".module or {}) ]; }\n");
	}
	try out.appendSlice(allocator, "\t\t\t\t{ _file = \"cogbox-user\"; imports = [ user.nixosModules.default ]; }\n" ++
		"\t\t\t];\n" ++
		"\t\t};\n" ++
		"\t};\n" ++
		"}\n");

	return try out.toOwnedSlice(allocator);
}

/// Escape for a double-quoted nix string: `\`, `"`, and `${`.
fn appendNixString(allocator: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) !void {
	for (s, 0..) |c, i| {
		switch (c) {
			'\\' => try out.appendSlice(allocator, "\\\\"),
			'"' => try out.appendSlice(allocator, "\\\""),
			'$' => {
				if (i + 1 < s.len and s[i + 1] == '{') {
					try out.appendSlice(allocator, "\\$");
				} else {
					try out.append(allocator, c);
				}
			},
			else => try out.append(allocator, c),
		}
	}
}

/// Atomically write `rendered` as <dir>/flake.nix (mkdir -p, .tmp + rename).
/// An existing flake.lock is KEPT (not deleted): the caller reconciles it with
/// `nix flake lock` after this write, so launch resolves from a coherent,
/// already-pinned lock instead of re-resolving every input (which a fresh-store
/// launch can't do offline for a git+ input). The lock is dropped only when the
/// last plugin is removed (removeCompositionFlake).
pub fn writeCompositionFlake(
	allocator: std.mem.Allocator,
	io: std.Io,
	dir: []const u8,
	rendered: []const u8,
) !void {
	const cwd = std.Io.Dir.cwd();
	try cwd.createDirPath(io, dir);

	const path = try std.fs.path.join(allocator, &.{ dir, "flake.nix" });
	defer allocator.free(path);
	const tmp_path = try std.fmt.allocPrint(allocator, "{s}.tmp", .{path});
	defer allocator.free(tmp_path);

	{
		const f = try cwd.createFile(io, tmp_path, .{ .truncate = true });
		defer f.close(io);
		var write_buf: [4096]u8 = undefined;
		var writer = f.writer(io, &write_buf);
		try writer.interface.writeAll(rendered);
		try writer.flush();
		try f.sync(io);
	}
	try cwd.rename(tmp_path, cwd, path, io);
}

/// Remove the generated flake (used when the last plugin is deleted, so the
/// launcher falls back to the plain per-instance flake path).
pub fn removeCompositionFlake(allocator: std.mem.Allocator, io: std.Io, dir: []const u8) !void {
	const cwd = std.Io.Dir.cwd();
	for ([_][]const u8{ "flake.nix", "flake.nix.tmp", "flake.lock" }) |f| {
		const path = try std.fs.path.join(allocator, &.{ dir, f });
		defer allocator.free(path);
		cwd.deleteFile(io, path) catch {};
	}
}
