const std = @import("std");
const compose = @import("compose.zig");
const t = std.testing;

test "render refuses zero plugins" {
	try t.expectError(error.NoPlugins, compose.render(t.allocator, "default", "/cfg/flake", "/cfg/plugin-sources", &.{}));
}

test "golden render: one plugin (hydrated -> path: input)" {
	const out = try compose.render(t.allocator, "default", "/home/u/.config/cogbox/instances/default/flake", "/home/u/.config/cogbox/instances/default/plugin-sources", &.{
		.{ .name = "myplugin", .locked_url = "github:o/myplugin/abc123?narHash=sha256-AAAA", .has_source = true },
	});
	defer t.allocator.free(out);

	const expected =
		"# GENERATED by 'cogbox plugin' -- DO NOT EDIT.\n" ++
		"# Regenerated from config.json (.plugins) on every plugin add/del/update.\n" ++
		"{\n" ++
		"\tdescription = \"cogbox plugin composition for instance 'default'\";\n" ++
		"\n" ++
		"\tinputs = {\n" ++
		"\t\tuser.url = \"path:/home/u/.config/cogbox/instances/default/flake\";\n" ++
		"\t\t\"p-myplugin\".url = \"path:/home/u/.config/cogbox/instances/default/plugin-sources/myplugin\";\n" ++
		"\t};\n" ++
		"\n" ++
		"\toutputs = { self, user, ... }@inputs: {\n" ++
		"\t\tnixosModules.default = {\n" ++
		"\t\t\timports = [\n" ++
		"\t\t\t\t{ _file = \"p-myplugin\"; imports = [ (inputs.\"p-myplugin\".cogboxPlugins.\"default\".module or {}) ]; }\n" ++
		"\t\t\t\t{ _file = \"cogbox-user\"; imports = [ user.nixosModules.default ]; }\n" ++
		"\t\t\t];\n" ++
		"\t\t};\n" ++
		"\t};\n" ++
		"}\n";
	try t.expectEqualStrings(expected, out);
}

test "hydrated source emits path: input; unhydrated falls back to locked URL" {
	// has_source=true -> a `path:<sources_dir>/<name>` input (offline at launch).
	const hydrated = try compose.render(t.allocator, "default", "/cfg/flake", "/cfg/plugin-sources", &.{
		.{ .name = "p", .locked_url = "git+https://git.example.com/o/r?ref=main&rev=deadbeef", .has_source = true },
	});
	defer t.allocator.free(hydrated);
	try t.expect(std.mem.indexOf(u8, hydrated, "\"p-p\".url = \"path:/cfg/plugin-sources/p\";") != null);
	// The locked git URL must NOT appear when the source is materialized.
	try t.expect(std.mem.indexOf(u8, hydrated, "git.example.com") == null);

	// has_source=false (migration fallback) -> the locked URL verbatim.
	const fallback = try compose.render(t.allocator, "default", "/cfg/flake", "/cfg/plugin-sources", &.{
		.{ .name = "p", .locked_url = "git+https://git.example.com/o/r?ref=main&rev=deadbeef", .has_source = false },
	});
	defer t.allocator.free(fallback);
	try t.expect(std.mem.indexOf(u8, fallback, "\"p-p\".url = \"git+https://git.example.com/o/r?ref=main&rev=deadbeef\";") != null);
	try t.expect(std.mem.indexOf(u8, fallback, "path:/cfg/plugin-sources/p") == null);
}

test "two plugins keep config order, user module last" {
	const out = try compose.render(t.allocator, "work", "/cfg/flake", "/cfg/plugin-sources", &.{
		.{ .name = "alpha", .locked_url = "path:/a?narHash=sha256-A" },
		.{ .name = "beta", .locked_url = "path:/b?narHash=sha256-B" },
	});
	defer t.allocator.free(out);

	const a_in = std.mem.indexOf(u8, out, "\"p-alpha\".url").?;
	const b_in = std.mem.indexOf(u8, out, "\"p-beta\".url").?;
	try t.expect(a_in < b_in);

	const a_imp = std.mem.indexOf(u8, out, "{ _file = \"p-alpha\"; imports = [ (inputs.\"p-alpha\".cogboxPlugins.\"default\".module or {}) ]; }").?;
	const b_imp = std.mem.indexOf(u8, out, "{ _file = \"p-beta\"; imports = [ (inputs.\"p-beta\".cogboxPlugins.\"default\".module or {}) ]; }").?;
	const user_imp = std.mem.indexOf(u8, out, "{ _file = \"cogbox-user\"; imports = [ user.nixosModules.default ]; }\n\t\t\t];").?;
	try t.expect(a_imp < b_imp);
	try t.expect(b_imp < user_imp);
	try t.expect(std.mem.indexOf(u8, out, "instance 'work'") != null);
}

test "every import is _file-tagged with its plugin's install name" {
	// The guest brain reads these tags back out of
	// options.cogbox.contents.definitionsWithLocations to attribute a
	// colliding skill/agent/command/rule to a plugin, so the tag must match
	// the input attr name exactly (`p-<name>`) and the user flake must carry
	// the distinct `cogbox-user` marker that keeps its content unqualified.
	const out = try compose.render(t.allocator, "default", "/cfg/flake", "/cfg/plugin-sources", &.{
		.{ .name = "obs-plugin", .locked_url = "path:/a?narHash=sha256-A" },
		.{ .name = "demo-plugin", .locked_url = "path:/b?narHash=sha256-B", .attr = "extra" },
	});
	defer t.allocator.free(out);

	try t.expect(std.mem.indexOf(u8, out, "{ _file = \"p-obs-plugin\"; imports = [ (inputs.\"p-obs-plugin\".cogboxPlugins.\"default\".module or {}) ]; }") != null);
	try t.expect(std.mem.indexOf(u8, out, "{ _file = \"p-demo-plugin\"; imports = [ (inputs.\"p-demo-plugin\".cogboxPlugins.\"extra\".module or {}) ]; }") != null);
	try t.expect(std.mem.indexOf(u8, out, "{ _file = \"cogbox-user\"; imports = [ user.nixosModules.default ]; }") != null);
	// No untagged import may survive: an untagged root cannot be qualified.
	try t.expect(std.mem.indexOf(u8, out, "\t\t\t\t(inputs.") == null);
	try t.expect(std.mem.indexOf(u8, out, "\t\t\t\tuser.nixosModules.default\n") == null);
}

test "non-default module attrs are emitted quoted" {
	const out = try compose.render(t.allocator, "default", "/cfg/flake", "/cfg/plugin-sources", &.{
		.{ .name = "hello", .locked_url = "path:/m?narHash=sha256-M" },
		.{ .name = "extra", .locked_url = "path:/m?narHash=sha256-M", .attr = "extra" },
	});
	defer t.allocator.free(out);

	// Same flake URL twice (two modules of one flake) is fine: two pinned
	// inputs that resolve to the same store path.
	try t.expect(std.mem.indexOf(u8, out, "(inputs.\"p-hello\".cogboxPlugins.\"default\".module or {})") != null);
	try t.expect(std.mem.indexOf(u8, out, "(inputs.\"p-extra\".cogboxPlugins.\"extra\".module or {})") != null);
}

test "nix string escaping in urls and paths" {
	const out = try compose.render(t.allocator, "default", "/odd \"dir\"/flake", "/odd \"dir\"/plugin-sources", &.{
		.{ .name = "x", .locked_url = "path:/p?x=${q}&y=a\\b" },
	});
	defer t.allocator.free(out);

	try t.expect(std.mem.indexOf(u8, out, "path:/odd \\\"dir\\\"/flake") != null);
	try t.expect(std.mem.indexOf(u8, out, "\\${q}") != null);
	try t.expect(std.mem.indexOf(u8, out, "a\\\\b") != null);
}

test "hydrated source path is nix-string escaped" {
	// The sources_dir and name both flow through appendNixString.
	const out = try compose.render(t.allocator, "default", "/cfg/flake", "/odd \"dir\"/plugin-sources", &.{
		.{ .name = "x", .locked_url = "ignored", .has_source = true },
	});
	defer t.allocator.free(out);
	try t.expect(std.mem.indexOf(u8, out, "path:/odd \\\"dir\\\"/plugin-sources/x") != null);
}

test "hydrated subdir plugin carries ?dir= on the path: input" {
	// nix flake metadata's .path is the repo ROOT for a ?dir= flake, so the
	// path: rewrite must re-add the dir to locate the flake in the tree.
	const out = try compose.render(t.allocator, "default", "/cfg/flake", "/cfg/plugin-sources", &.{
		.{ .name = "sub", .locked_url = "github:o/r/abc?dir=flake&narHash=sha256-A", .has_source = true, .dir = "flake" },
	});
	defer t.allocator.free(out);
	try t.expect(std.mem.indexOf(u8, out, "\"p-sub\".url = \"path:/cfg/plugin-sources/sub?dir=flake\";") != null);
}
